import products from "./products.js";

// Data object
const state = {
  selectedColor: null,
  selectedSize: null,
  selectedVariant: null,
  quantity: 1,
  cart: [],
};

function uniqueColors(theArray) {
  let productColors = theArray.reduce((prev, current) => {
    // checking if the current color exist in the array
    if (!prev.includes(current.color)) {
      prev.push(current.color);
    }
    return prev;
  }, []);
  return productColors;
}

function renderProduct() {
  // Main product wrapper
  const mainProductWrapper = document.querySelector("#main-product-wrapper");

  // display unique color
  const colors = uniqueColors(products.variants);

  let defaultColor = state.selectedColor
    ? state.selectedColor
    : products.variants[0].color;

  // display unique sizes
  const filterSelectedColor = products.variants.filter(
    (product) => product.color === defaultColor,
  );

  const sizes = filterSelectedColor.reduce((prev, current) => {
    if (!prev.includes(current.size)) {
      prev.push(current.size);
    }
    return prev;
  }, []);

  console.log(1);

  function UI() {
    return `
          <!-- LEFT SIDE: Images -->
          <div class="space-y-4">
            <!-- Main Image -->
            <div class="aspect-square bg-gray-100 rounded-lg overflow-hidden">
              <img
                id="main-image"
                src="${products.images.black[0]}"
                alt="Product Image"
                class="w-full h-full object-cover"
              />
            </div>

            <!-- Thumbnail Images -->
            <div class="grid grid-cols-4 gap-2" id="thumbnails-image">
              <!-- Generated by JavaScript -->
                <img
                id="main-image"
                src="${products.images.black[1]}"
                alt="Product Image"
                class="w-full h-full object-cover"
              />

            </div>
          </div>

          <!-- RIGHT SIDE: Product Info -->
          <div class="space-y-6">
            <!-- Product Title -->
            <div>
              <h1
                id="product-title"
                class="text-3xl font-bold text-gray-900"
              >${products.title}</h1>
              <p id="product-description" class="text-gray-600 mt-2">${products.description}</p>
            </div>

            <!-- Price -->
            <div class="flex items-baseline gap-2">
              <span
                id="product-price"
                class="text-3xl font-bold text-gray-900"
              >$${products.variants[0].price.toFixed(2)}</span>
            </div>

            <!-- Stock Status -->
            <div id="stock-status" class="text-sm font-medium">
              <!-- Generated by JavaScript -->
              In stock: ${products.variants[0].stock}
            </div>

            <!-- Variant Info (Debug - Remove in production) -->
            <div
              id="variant-info"
              class="text-base flex flex-col text-gray-500 bg-gray-50 p-3 rounded"
            >
              <!-- Shows selected variant details -->
              <span class="capitalize">Selected color: ${colors[0]}</span>
              <span class="capitalize">Selected size:</span>

            </div>

            <!-- Color Selector -->
            <div class="space-y-3">
              <label class="block text-sm font-medium text-gray-700">
                Color:
                <span id="selected-color-text" class="text-gray-900 capitalize font-semibold"
                  >${state.selectedColor ? state.selectedColor : colors[0]}</span
                >
              </label>
              <div class="flex gap-3" id="color-swatches">
                <!-- Generated by JavaScript -->
                  ${colors
                    .map((color) => {
                      return `<span style="background-color:${color}" class="swatches w-7 h-7 p-4 rounded-full  cursor-pointer flex justify-center border items-center text-sm blocks"></span>`;
                    })
                    .join("")}
              </div>
            </div>

            <!-- Size Selector -->
            <div class="space-y-3">
              <label class="block text-sm font-medium text-gray-700">
                Size:
                <span id="selected-size-text" class="text-gray-900 font-semibold"
                  >
                    ${state.selectedSize ? state.selectedSize : ""}
                  </span
                >
              </label>
              <div class="flex gap-2" id="size-buttons">
                <!-- Generated by JavaScript -->
                ${sizes
                  .map((size) => {
                    return `<span class="w-6 h-6 text-sm flex justify-center items-center cursor-pointer rounded border border-gray-800">${size}</span>`;
                  })
                  .join("")}
                  
              </div>
            </div>

            <!-- Quantity Selector -->
            <div class="space-y-3">
              <label class="block text-sm font-medium text-gray-700"
                >Quantity</label
              >
              <div class="flex items-center gap-3">
                <button
                  id="qty-decrease"
                  class="w-10 h-10 rounded-md border border-gray-300 hover:bg-gray-50 flex items-center justify-center cursor-pointer font-semibold"
                >
                  −
                </button>
                <input
                  type="number"
                  id="quantity"
                  value="1"
                  min="1"
                  max="10"
                  class="w-20 h-10 text-center border border-gray-300 rounded-md"
                />
                <button
                  id="qty-increase"
                  class="w-10 h-10 rounded-md border border-gray-300 hover:bg-gray-50 flex items-center justify-center cursor-pointer  font-semibold"
                >
                  +
                </button>
              </div>
            </div>

            <!-- Add to Cart Button -->
            <button
              id="add-to-cart"
              class="w-full bg-black text-white py-4 px-6 rounded-md font-semibold hover:bg-gray-800 transition disabled:bg-gray-300 disabled:cursor-not-allowed"
            >
              Add to Cart
            </button>

            <!-- Message Display -->
            <div id="message" class="hidden"></div>
          </div>
      `;
  }
  mainProductWrapper.innerHTML = UI();
}
renderProduct();

function selectColorVariant() {
  const swatches = document.querySelectorAll(".swatches ");

  swatches.forEach((swatche, index) => {
    swatche.addEventListener("click", () => {
      //
      const select = products.variants.filter(
        (variant) => variant.color === swatche.style.backgroundColor,
      );

      state.selectedColor = uniqueColors(select).toString();
      console.log(state.selectedColor);

      renderProduct();
    });
  });
}

selectColorVariant();
