import products from "./products.js";

// Data object
const state = {
  displayColors: null,
  selectedColor: null,
  showSizes: null,
  selectedSize: null,
  selectedVariant: null,
  showStock: null,
  quantity: 1,
  cart: [],
};

// render product
function renderProduct() {
  // Main product wrapper
  const mainProductWrapper = document.querySelector("#main-product-wrapper");

  // display all the colors on the page
  state.displayColors = displayColors(products.variants);

  // Defautl color
  state.selectedColor = state.selectedColor
    ? state.selectedColor
    : state.displayColors[0];

  // display all the size based of default color
  state.showSizes = displaySizes(state.selectedColor);
  console.log(state.showSizes);

  // default size
  state.selectedSize = state.selectedSize
    ? state.selectedSize
    : state.showSizes[0].size;

  mainProductWrapper.innerHTML = `
  <!-- LEFT SIDE: Images -->
  <div class="space-y-4">
    <!-- Main Image -->
    <div class="aspect-square bg-gray-100 rounded-lg overflow-hidden">
      <img
        id="main-image"
        src="${products.images.black[0]}"
        alt="Product Image"
        class="w-full h-full object-cover"
      />
    </div>

    <!-- Thumbnail Images -->
    <div class="grid grid-cols-4 gap-2" id="thumbnails-image">
      <!-- Generated by JavaScript -->
        <img
        id="main-image"
        src="${products.images.black[1]}"
        alt="Product Image"
        class="w-full h-full object-cover"
      />

    </div>
  </div>

  <!-- RIGHT SIDE: Product Info -->
  <div class="space-y-6">
    <!-- Product Title -->
    <div>
      <h1
        id="product-title"
        class="text-3xl font-bold text-gray-900"
      >${products.title}</h1>
      <p id="product-description" class="text-gray-600 mt-2">${products.description}</p>
    </div>

    <!-- Price -->
    <div class="flex items-baseline gap-2">
      <span
        id="product-price"
        class="text-3xl font-bold text-gray-900"
      >$${products.variants[0].price.toFixed(2)}</span>
    </div>

    <!-- Stock Status -->
    <div id="stock-status" class="text-sm font-medium">
      <!-- Generated by JavaScript -->
      In stock: ${state.selectedSize}
    </div>

    <!-- Color Selector -->
    <div class="space-y-3">
      <label class="block text-sm font-medium text-gray-700">
        Color:
        <span id="selected-color-text" class="text-gray-900 capitalize font-semibold"
          >${state.selectedColor}</span
        >
      </label>
      <div class="flex gap-3" id="color-swatches">
        <!-- Generated by JavaScript -->
         ${state.displayColors
           .map((swatche) => {
             return `<span style="background-color:${swatche}" data-color="${swatche}" class="w-7 h-7 block border rounded-full colors cursor-pointer"></span>`;
           })
           .join("")}
      </div>
    </div>

    <!-- Size Selector -->
    <div class="space-y-3">
      <label class="block text-sm font-medium text-gray-700">
        Size:
        <span id="selected-size-text" class="text-gray-900 font-semibold"
          >
          ${state.selectedSize}
          </span
        >
      </label>
      <div class="flex gap-2" id="size-buttons">
        <!-- Generated by JavaScript -->
        ${state.showSizes

          .map((size) => {
            return `<span class="w-7 h-7 ${size.stock === 0 ? "pointer-events-none opacity-50 grayscale!" : "cursor-pointer"}  rounded text-sm border flex justify-center items-center">${size.size}</span>`;
          })
          .join("")}
          
      </div>
    </div>

    <!-- Quantity Selector -->
    <div class="space-y-3">
      <label class="block text-sm font-medium text-gray-700"
        >Quantity</label
      >
      <div class="flex items-center gap-3">
        <button
          id="qty-decrease"
          class="w-10 h-10 rounded-md border border-gray-300 hover:bg-gray-50 flex items-center justify-center cursor-pointer font-semibold"
        >
          −
        </button>
        <input
          type="number"
          id="quantity"
          value="1"
          min="1"
          max="10"
          class="w-20 h-10 text-center border border-gray-300 rounded-md"
        />
        <button
          id="qty-increase"
          class="w-10 h-10 rounded-md border border-gray-300 hover:bg-gray-50 flex items-center justify-center cursor-pointer  font-semibold"
        >
          +
        </button>
      </div>
    </div>

    <!-- Add to Cart Button -->
    <button
      id="add-to-cart"
      class="w-full bg-black text-white py-4 px-6 rounded-md font-semibold hover:bg-gray-800 transition disabled:bg-gray-300 disabled:cursor-not-allowed"
    >
      Add to Cart
    </button>

    <!-- Message Display -->
    <div id="message" class="hidden"></div>
  </div>
  `;
}

renderProduct();

// Display unique colors for each variants
function displayColors(data) {
  const getColors = new Set();
  data.forEach((swatche) => {
    getColors.add(swatche.color);
  });
  return [...getColors];
}
// display sizes based on the default color
function displaySizes(defaultColor) {
  // Set default color
  return products.variants.filter(
    (variant_size) => variant_size.color === defaultColor,
  );
}

// This function will display data based on the clicked color
function swatches() {
  //grab the colors
  const colors = document.querySelectorAll(".colors");

  colors.forEach((color) => {
    color.addEventListener("click", () => {});
  });
}

swatches();
